<?php

/**
 * @file
 * Tracks node popularity and extends Solr ranking for each node with its popularity.
 */

/**
 * Implements hook_exit().
 *
 * Gathers statistics for page accesses.
 */
function apachesolr_popularity_exit() {
  
  global $user;

  drupal_bootstrap(DRUPAL_BOOTSTRAP_VARIABLES);

  if (variable_get('statistics_count_content_views', 0)) {
    // We are counting content views.
    if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == NULL) {
      // A node has been viewed, so update the node's counters.
      db_merge('node_counter')
        ->key(array('nid' => arg(1)))
        ->fields(array(
          'recentcount' => 1,
        ))
        ->expression('recentcount', 'recentcount + 1')
        ->execute();
    }
  }
}

/**
 * Implements hook_menu().
 */
function statistics_menu() {
  $items['admin/reports/popularpages'] = array(
    'title' => 'Popular pages',
    'description' => 'View most popular pages.',
    'page callback' => 'apachesolr_top_pages',
//TODO    'page callback' => 'statistics_top_pages',
    'access arguments' => array('administer search'),
//  'access arguments' => array('access statistics'),
    'file' => 'apachesolr_popularity.admin.inc',
  );
  $items['admin/config/search/apachesolr/apachesolr_popularity'] = array(
    'title' => 'Apache Solr Popularity',
    'description' => 'Configure Apache Solr Popularity Tracking.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apachesolr_popularity_form'),
//  'page arguments' => array('statistics_settings_form'),
    'access arguments' => array('administer search'),
//  'access arguments' => array('access statistics'),
    'file' => 'apachesolr_popularity.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}